name: webview_poc
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin: "^0.1.0+1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true